on:
  push:
    branches:
      - main

name: CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: |
          yarn install
      - name: Test
        run: |
          yarn test
